version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db_otp
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8'
    ports:
      - '${DATABASE_PORT}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
